---
AllCops:
  TargetRubyVersion: 3.1.6p260
  NewCops: disable
  Exclude:
  - Gemfile

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: true
  Regex: !ruby/regexp '/^.{3,100}$/'

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false